import random
import hashlib
import datetime

# Configuration
NUM_USERS = 50
NUM_TOPICS = 20
NUM_CONTENT = 200
NUM_FEEDBACK = 500
NUM_SESSIONS = 100

# Helper to hash password (must match backend's SHA256 logic)
def hash_password(password):
    return hashlib.sha256(password.encode()).hexdigest()

# Data Pools
NAMES = ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Heidi", "Ivan", "Judy", "Mallory", "Niaj", "Olivia", "Peggy", "Quentin", "Rupert", "Sybil", "Trent", "Victor", "Walter"]
SURNAMES = ["Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis", "Rodriguez", "Martinez"]
TOPICS = [
    "Technology", "Productivity", "Mental Health", "Music", "Movies", "Gaming", "Reading", "Fitness", "Meditation", "Cooking",
    "Science", "History", "Art", "Design", "Photography", "Travel", "Fashion", "Sports", "Politics", "Economics"
]
CONTENT_TITLES = [
    "10 Tips for Better Focus", "Why You Should Meditate", "Top 5 Movies of 2024", "Understanding Quantum Physics", "Healthy Recipes for Dinner",
    "Best Coding Practices", "How to Manage Stress", "The History of Rome", "Travel Guide to Japan", "Yoga for Beginners"
]

def generate_sql():
    sql = []
    sql.append("-- Mock Data Generation Script")
    sql.append("-- Generated by Be-Productive Assistant")
    sql.append("")

    # 1. Users
    users = []
    print("Generating Users...")
    for i in range(1, NUM_USERS + 1):
        name = f"{random.choice(NAMES)} {random.choice(SURNAMES)}"
        email = f"user{i}@example.com"
        password = "password123" # Default password
        hashed = hash_password(password)
        users.append(f"({i}, '{name}', '{email}', '{hashed}', 'NEUTRO')")
    
    sql.append(f"INSERT INTO usuario (id_usuario, nome, email, senha_criptografada, estado_emocional_inferido) VALUES")
    sql.append(",\n".join(users) + ";")
    sql.append("")

    # 2. Topics (Ensure we don't duplicate existing ones if running on top of seed)
    # We'll assume fresh start or use INSERT IGNORE logic if needed, but standard INSERT is requested.
    # The existing seed has IDs 1-10. We'll add 11-30.
    topics = []
    print("Generating Topics...")
    for i, topic_name in enumerate(TOPICS, start=11):
        desc = f"Description for {topic_name}"
        topics.append(f"({i}, '{topic_name}', '{desc}')")

    sql.append(f"INSERT INTO topico (id_topico, nome_topico, descricao) VALUES")
    sql.append(",\n".join(topics) + ";")
    sql.append("")

    # 3. User-Topics
    user_topics = []
    print("Generating User-Topics...")
    seen_ut = set()
    for user_id in range(1, NUM_USERS + 1):
        # Assign 3-5 topics per user
        num_topics = random.randint(3, 5)
        selected_topics = random.sample(range(1, 30), num_topics) # mix of old and new topics
        for topic_id in selected_topics:
            if (user_id, topic_id) not in seen_ut:
                user_topics.append(f"({user_id}, {topic_id})")
                seen_ut.add((user_id, topic_id))
    
    sql.append(f"INSERT INTO usuario_topico (id_usuario, id_topico) VALUES")
    sql.append(",\n".join(user_topics) + ";")
    sql.append("")

    # 4. Content
    content_list = []
    print("Generating Content...")
    for i in range(1, NUM_CONTENT + 1):
        title = f"{random.choice(CONTENT_TITLES)} #{i}"
        body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
        media_type = random.choice(['TEXTO', 'VIDEO', 'AUDIO'])
        category = random.choice(['PRODUTIVIDADE', 'ENTRETENIMENTO'])
        autor_id = random.randint(1, NUM_USERS)
        # Random dates in 2024-2025
        date = datetime.datetime(2025, random.randint(1, 12), random.randint(1, 28)).strftime('%Y-%m-%d %H:%M:%S')
        score = round(random.uniform(0.1, 0.9), 4)

        content_list.append(f"({i}, '{title}', '{body}', '{media_type}', '{category}', {autor_id}, '{date}', '{score}')")

    sql.append(f"INSERT INTO conteudo (id_conteudo, titulo, corpo, tipo_de_midia, categoria, autor_id, data_publicacao, score_de_qualidade) VALUES")
    sql.append(",\n".join(content_list) + ";")
    sql.append("")

    # 5. Connect Content to Topics
    content_topics = []
    print("Generating Content-Topics...")
    seen_ct = set()
    for content_id in range(1, NUM_CONTENT + 1):
        topic_id = random.randint(1, 30) # at least one topic
        content_topics.append(f"({content_id}, {topic_id})")
    
    sql.append(f"INSERT INTO conteudo_topico (id_conteudo, id_topico) VALUES")
    sql.append(",\n".join(content_topics) + ";")
    sql.append("")

    # 6. Feedback
    feedbacks = []
    print("Generating Feedback...")
    seen_feed = set()
    for i in range(1, NUM_FEEDBACK + 1):
        user_id = random.randint(1, NUM_USERS)
        content_id = random.randint(1, NUM_CONTENT)
        if (user_id, content_id) not in seen_feed:
            seen_feed.add((user_id, content_id))
            type_ = random.choice(['util', 'nao_relevante', 'relaxante'])
            feedbacks.append(f"({i}, {content_id}, {user_id}, '{type_}')")

    sql.append(f"INSERT INTO feedback_conteudo (id_feedback, id_conteudo, id_usuario, tipo) VALUES")
    sql.append(",\n".join(feedbacks) + ";")
    sql.append("")

    # 7. Focus Sessions
    sessions = []
    print("Generating Focus Sessions...")
    for i in range(1, NUM_SESSIONS + 1):
        user_id = random.randint(1, NUM_USERS)
        start = datetime.datetime(2025, random.randint(1, 12), random.randint(1, 28), random.randint(8, 20), 0, 0)
        duration_prod = random.randint(10, 60)
        duration_ent = random.randint(5, 20)
        end = start + datetime.timedelta(minutes=duration_prod + duration_ent)
        
        start_str = start.strftime('%Y-%m-%d %H:%M:%S')
        end_str = end.strftime('%Y-%m-%d %H:%M:%S')
        feedback_sessao = random.choice(['NULL', random.randint(1, 5)])

        sessions.append(f"({i}, {user_id}, '{start_str}', '{end_str}', {duration_prod}, {duration_ent}, {feedback_sessao})")

    sql.append(f"INSERT INTO sessao_de_uso (id_sessao, usuario_associado_id, hora_inicio, hora_fim, tempo_produtividade_realizado, tempo_entretenimento_realizado, feedback_da_sessao) VALUES")
    sql.append(",\n".join(sessions) + ";")
    
    return "\n".join(sql)

if __name__ == "__main__":
    sql_content = generate_sql()
    with open("mock_data.sql", "w", encoding="utf-8") as f:
        f.write(sql_content)
    print("Successfully generated mock_data.sql")
